/*Mock Omeka Collections*/
export const  mockEmptyCollections = []
export const  mockCollections = [
	{
		"id":3,
		"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/collections\/3",
		"public":true,
		"featured":true,
		"added":"2016-08-15T14:50:20+00:00",
		"modified":"2019-07-09T15:05:29+00:00",
		"owner":{
			"id":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/users\/1",
			"resource":"users"
		},
		"items":{
			"count":0,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/items?collection=3",
			"resource":"items"
		},
		"element_texts":[
			{
				"html":false,
				"text":"Tools",
				"element_set":{
					"id":1,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/element_sets\/1",
					"name":"Dublin Core",
					"resource":"element_sets"
				},
				"element":{
					"id":50,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/elements\/50",
					"name":"Title",
					"resource":"elements"
				}
			}
		],
		"extended_resources":[

		]
	},
	{
		"id":6,
		"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/collections\/6",
		"public":true,
		"featured":true,
		"added":"2016-08-15T14:50:58+00:00",
		"modified":"2019-07-09T15:05:24+00:00",
		"owner":{
			"id":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/users\/1",
			"resource":"users"
		},
		"items":{
			"count":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/items?collection=6",
			"resource":"items"
		},
		"element_texts":[
			{
				"html":false,
				"text":"Paper Creations",
				"element_set":{
					"id":1,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/element_sets\/1",
					"name":"Dublin Core",
					"resource":"element_sets"
				},
				"element":{
					"id":50,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/elements\/50",
					"name":"Title",
					"resource":"elements"
				}
			}
		],
		"extended_resources":[

		]
	},
	{
		"id":7,
		"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/collections\/7",
		"public":true,
		"featured":true,
		"added":"2016-08-15T14:51:09+00:00",
		"modified":"2019-07-09T15:05:41+00:00",
		"owner":{
			"id":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/users\/1",
			"resource":"users"
		},
		"items":{
			"count":2,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/items?collection=7",
			"resource":"items"
		},
		"element_texts":[
			{
				"html":false,
				"text":"Artisans",
				"element_set":{
					"id":1,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/element_sets\/1",
					"name":"Dublin Core",
					"resource":"element_sets"
				},
				"element":{
					"id":50,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/elements\/50",
					"name":"Title",
					"resource":"elements"
				}
			}
		],
		"extended_resources":[

		]
    }]
    /*Mock Omeka Items*/
    export const mockEmptyItems = []
    
    export const mockItems = [
        {
		"id":1,
		"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/items\/1",
		"public":true,
		"featured":false,
		"added":"2016-08-15T17:06:38+00:00",
		"modified":"2019-07-09T14:43:38+00:00",
		"item_type":null,
		"collection":null,
		"owner":{
			"id":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/users\/1",
			"resource":"users"
		},
		"files":{
			"count":0,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/files?item=1",
			"resource":"files"
		},
		"tags":[
			{
				"id":2,
				"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/tags\/2",
				"name":"Archaeology",
				"resource":"tags"
			},
			{
				"id":3,
				"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/tags\/3",
				"name":"Environment",
				"resource":"tags"
			},
			{
				"id":4,
				"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/tags\/4",
				"name":"History",
				"resource":"tags"
			},
			{
				"id":1,
				"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/tags\/1",
				"name":"Location",
				"resource":"tags"
			}
		],
		"element_texts":[
			{
				"html":false,
				"text":"test",
				"element_set":{
					"id":1,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/element_sets\/1",
					"name":"Dublin Core",
					"resource":"element_sets"
				},
				"element":{
					"id":50,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/elements\/50",
					"name":"Title",
					"resource":"elements"
				}
			}
		],
		"extended_resources":[

		]
	},
	{
		"id":2,
		"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/items\/2",
		"public":true,
		"featured":false,
		"added":"2016-08-15T19:37:18+00:00",
		"modified":"2019-07-09T14:43:23+00:00",
		"item_type":null,
		"collection":{
			"id":6,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/collections\/6",
			"resource":"collections"
		},
		"owner":{
			"id":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/users\/1",
			"resource":"users"
		},
		"files":{
			"count":0,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/files?item=2",
			"resource":"files"
		},
		"tags":[
			{
				"id":5,
				"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/tags\/5",
				"name":"Fibers",
				"resource":"tags"
			},
			{
				"id":6,
				"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/tags\/6",
				"name":"Materials",
				"resource":"tags"
			},
			{
				"id":7,
				"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/tags\/7",
				"name":"Preparation",
				"resource":"tags"
			}
		],
		"element_texts":[
			{
				"html":false,
				"text":"test 2",
				"element_set":{
					"id":1,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/element_sets\/1",
					"name":"Dublin Core",
					"resource":"element_sets"
				},
				"element":{
					"id":50,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/elements\/50",
					"name":"Title",
					"resource":"elements"
				}
			}
		],
		"extended_resources":[

		]
	},
	{
		"id":3,
		"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/items\/3",
		"public":true,
		"featured":false,
		"added":"2016-08-15T19:37:38+00:00",
		"modified":"2016-08-15T19:37:38+00:00",
		"item_type":null,
		"collection":null,
		"owner":{
			"id":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/users\/1",
			"resource":"users"
		},
		"files":{
			"count":0,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/files?item=3",
			"resource":"files"
		},
		"tags":[
			{
				"id":8,
				"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/tags\/8",
				"name":"Tools",
				"resource":"tags"
			}
		],
		"element_texts":[
			{
				"html":false,
				"text":"test3",
				"element_set":{
					"id":1,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/element_sets\/1",
					"name":"Dublin Core",
					"resource":"element_sets"
				},
				"element":{
					"id":50,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/elements\/50",
					"name":"Title",
					"resource":"elements"
				}
			}
		],
		"extended_resources":[

		]
	},
	{
		"id":4,
		"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/items\/4",
		"public":true,
		"featured":false,
		"added":"2016-08-15T19:38:02+00:00",
		"modified":"2019-07-09T14:43:13+00:00",
		"item_type":null,
		"collection":null,
		"owner":{
			"id":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/users\/1",
			"resource":"users"
		},
		"files":{
			"count":0,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/files?item=4",
			"resource":"files"
		},
		"tags":[
			{
				"id":9,
				"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/tags\/9",
				"name":"Sheetmaking",
				"resource":"tags"
			}
		],
		"element_texts":[
			{
				"html":false,
				"text":"test4",
				"element_set":{
					"id":1,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/element_sets\/1",
					"name":"Dublin Core",
					"resource":"element_sets"
				},
				"element":{
					"id":50,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/elements\/50",
					"name":"Title",
					"resource":"elements"
				}
			}
		],
		"extended_resources":[

		]
	},
	{
		"id":5,
		"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/items\/5",
		"public":true,
		"featured":false,
		"added":"2016-08-15T19:38:46+00:00",
		"modified":"2019-07-09T14:43:02+00:00",
		"item_type":null,
		"collection":null,
		"owner":{
			"id":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/users\/1",
			"resource":"users"
		},
		"files":{
			"count":0,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/files?item=5",
			"resource":"files"
		},
		"tags":[
			{
				"id":11,
				"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/tags\/11",
				"name":"Finishing",
				"resource":"tags"
			},
			{
				"id":10,
				"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/tags\/10",
				"name":"Sheet Drying",
				"resource":"tags"
			}
		],
		"element_texts":[
			{
				"html":false,
				"text":"test5",
				"element_set":{
					"id":1,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/element_sets\/1",
					"name":"Dublin Core",
					"resource":"element_sets"
				},
				"element":{
					"id":50,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/elements\/50",
					"name":"Title",
					"resource":"elements"
				}
			}
		],
		"extended_resources":[

		]
	},
	{
		"id":6,
		"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/items\/6",
		"public":true,
		"featured":false,
		"added":"2016-08-15T19:39:00+00:00",
		"modified":"2019-07-09T14:43:02+00:00",
		"item_type":null,
		"collection":null,
		"owner":{
			"id":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/users\/1",
			"resource":"users"
		},
		"files":{
			"count":0,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/files?item=6",
			"resource":"files"
		},
		"tags":[
			{
				"id":12,
				"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/tags\/12",
				"name":"Paper Creations",
				"resource":"tags"
			}
		],
		"element_texts":[
			{
				"html":false,
				"text":"test6",
				"element_set":{
					"id":1,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/element_sets\/1",
					"name":"Dublin Core",
					"resource":"element_sets"
				},
				"element":{
					"id":50,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/elements\/50",
					"name":"Title",
					"resource":"elements"
				}
			}
		],
		"extended_resources":[

		]
	},
	{
		"id":7,
		"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/items\/7",
		"public":true,
		"featured":false,
		"added":"2016-08-15T19:39:20+00:00",
		"modified":"2019-07-09T14:42:53+00:00",
		"item_type":null,
		"collection":{
			"id":7,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/collections\/7",
			"resource":"collections"
		},
		"owner":{
			"id":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/users\/1",
			"resource":"users"
		},
		"files":{
			"count":0,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/files?item=7",
			"resource":"files"
		},
		"tags":[
			{
				"id":13,
				"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/tags\/13",
				"name":"Artisans",
				"resource":"tags"
			}
		],
		"element_texts":[
			{
				"html":false,
				"text":"test7",
				"element_set":{
					"id":1,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/element_sets\/1",
					"name":"Dublin Core",
					"resource":"element_sets"
				},
				"element":{
					"id":50,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/elements\/50",
					"name":"Title",
					"resource":"elements"
				}
			}
		],
		"extended_resources":[

		]
	},
	{
		"id":8,
		"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/items\/8",
		"public":true,
		"featured":false,
		"added":"2016-08-24T15:43:15+00:00",
		"modified":"2019-07-09T14:42:53+00:00",
		"item_type":null,
		"collection":{
			"id":7,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/collections\/7",
			"resource":"collections"
		},
		"owner":{
			"id":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/users\/1",
			"resource":"users"
		},
		"files":{
			"count":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/files?item=8",
			"resource":"files"
		},
		"tags":[
			{
				"id":5,
				"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/tags\/5",
				"name":"Fibers",
				"resource":"tags"
			}
		],
		"element_texts":[
			{
				"html":false,
				"text":"Test 8",
				"element_set":{
					"id":1,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/element_sets\/1",
					"name":"Dublin Core",
					"resource":"element_sets"
				},
				"element":{
					"id":50,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/elements\/50",
					"name":"Title",
					"resource":"elements"
				}
			}
		],
		"extended_resources":[

		]
	}]